CREATE TABLE IF NOT EXISTS GAME(
 GAME_ID INT NOT NULL,
  STATE VARCHAR(200) NOT NULL,
 PRIMARY KEY (GAME_ID));

 CREATE TABLE IF NOT EXISTS FIGURE(
  GAME_ID INT NOT NULL,
   FIGURE_ID INT NOT NULL,


 PRIMARY KEY (GAME_ID));

  CREATE TABLE IF NOT EXISTS FIGURE_TYPE(
    FIGURE_ID INT NOT NULL,
   COORDINATE VARCHAR(20000) NOT NULL,
   PRIMARY KEY (FIGURE_ID));

    CREATE TABLE IF NOT EXISTS MOVE(
     GAME_ID INT NOT NULL,
     MOVE_EVENT VARCHAR(200) NOT NULL
      );
